version: '3.8'

services:
  notification-app:
    image: poornagollakoti/notification-app:1.0.2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.dev.properties
    ports:
      - "3002:3000"
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis  # Refer to Redis service
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
