version: '3.8'

services:
  notification-app:
    image: diwali.azurecr.io/notification-app:1.0.6
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENV_FILE: .env.dev.properties
    ports:
      - "3002:3000" # Maps external port 3002 to internal port 3000 in the container
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis  # Refer to Redis service
      REDIS_PORT: 6379

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
