apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-configmap-dev
data:
  NODE_ENV: "local"
  APP_NAME: "NestJS"
  APP_DESCRIPTION: "Notification Service"
  APP_PORT: "3002"  # Updated Port
  APP_HOST: "http://52.170.235.122:3002"  # Updated Port
  APP_BASE_URL: "http://52.170.235.122:3002"  # Updated Port
  APP_VERSION: "1.0.0"
  APP_SWAGGER_PATH: "api-docs"
  CORS_ORIGIN: "*"
  CORS_CREDENTIALS: "true"
  CORS_EXPOSED_HEADERS: "Accept,authorization,Authentication,Content-Type,If-None-Match,SourceType"
  LOGGER_LEVEL: "info"
  LOGGER_FILE_NAME: "./logs/logs.log"
  SMTP_HOST: "smtp.hostinger.com"
  SMTP_PORT: "587"
  SMTP_USER: "chandra@heartsource.tech"
  FROM_EMAIL: "chandra@heartsource.tech"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
