apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app-deployment
  labels:
    app: notification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
      - name: notification-container
        image: diwali.azurecr.io/notification-app:1.0.4
        ports:
        - containerPort: 3000   # Should match the internal application port
        envFrom:
        - configMapRef:
            name: notification-configmap-dev
        - secretRef:
            name: notification-secret-dev
        # resources:
        #   limits:
        #     memory: "256Mi"
        #     cpu: "500m"
        #   requests:
        #     memory: "128Mi"
        #     cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-app-service
  labels:
    app: notification-app
spec:
  type: ClusterIP  
  selector:
    app: notification-app
  ports:
    - protocol: TCP
      port: 3002 # Expose this service on port 3002 externally
      targetPort: 3002 # Forward traffic to port 3000 inside the container