apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-app-deployment
  labels:
    app: notification-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
      - name: notification-container
        image: poornagollakoti/notification-app:1.0.2
        ports:
        - containerPort: 3002  # Updated Port
        envFrom:
        - configMapRef:
            name: notification-configmap-dev
        - secretRef:
            name: notification-secret-dev
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 3002  # Updated Port
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: "/health"
            port: 3002  # Updated Port
          initialDelaySeconds: 15
          periodSeconds: 20
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: notification-app-service
  labels:
    app: notification-app
spec:
  type: ClusterIP
  selector:
    app: notification-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3002  # Updated Port