# notification-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: notification-app-service
  labels:
    app: notification-app
spec:
  type: ClusterIP  # You can change to LoadBalancer for external access
  selector:
    app: notification-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
